### ISSUE TITLE
boost 1.69 doesn't compile with  VS 2017 /clr

### ISSUE THREAD

**Issue by BoostBugReporter** [boostorg/type_traits#111] opened 2019-01-15 13:27 UTC
[BoostConsole.zip](https://github.com/boostorg/boost/files/2759777/BoostConsole.zip)

If you try to compile this with  VS 2017 15.9.5 using boost 1.69 you get 60 errors and 48 warnings
(It does compile with boost 1.68)

Error	C2764	
     'C': template parameter not used or deducible in partial specialization 'boost::is_member_function_pointer<Ret(Args...)>'	
     boost\type_traits\detail\is_member_function_pointer_cxx_11.hpp	114	

Warning	C4561
	'__fastcall' incompatible with the '/clr' option: converting to '__stdcall'
	boost\type_traits\detail\is_member_function_pointer_cxx_11.hpp	120	

Error	C2953
	'boost::is_member_function_pointer<Ret(__stdcall C::* )(Args...)>': class template has already been defined	
	boost\type_traits\detail\is_member_function_pointer_cxx_11.hpp	120	
...

with best regards

  Hendrik

**Comment by jzmaddock** [comment] 2019-02-20 13:40
Sorry, must have missed this one - it's a duplicate of https://github.com/boostorg/type_traits/issues/99 and the linked commits from there contain the necessary fixes.

**Closed by jzmaddock** 2019-02-20 13:40 UTC
